# ClusterIP Service for Nginx Deployment
# This YAML file demonstrates how to create a Kubernetes Service of type ClusterIP for an Nginx Deployment.
# This service will route traffic to the Nginx pods based on the labels defined in the Deployment.
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: k8s-demo
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
