# ConfigMap for Nginx
# This YAML file demonstrates how to create a ConfigMap that contains custom Nginx configuration and an HTML file.
# The ConfigMap is then used in a Deployment to configure the Nginx server.

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: k8s-demo
data:
  nginx.conf: |
    server {
      listen 80;
      server_name localhost;
      
      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
      }
      
      error_page 500 502 503 504 /50x.html;
      location = /50x.html {
        root /usr/share/nginx/html;
      }
    }
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Welcome to K8s CKA Demo</title>
    </head>
    <body>
      <h1>Success! Custom config mounted from ConfigMap</h1>
    </body>
    </html>
