# Database credentials secret
# This YAML file demonstrates how to create a Kubernetes Secret that stores database credentials.
# The Secret is then used in a Deployment to provide the credentials to the application.
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: k8s-demo
type: Opaque
data:
  username: YWRtaW4= # admin in base64
  password: UGFzc3dvcmQxMjM= # Password123 in base64
