# This YAML file demonstrates how to create a Kubernetes Deployment that uses a Secret.
# The Deployment runs a simple application that uses the Secret to access database credentials.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-with-secrets
  namespace: k8s-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-demo
  template:
    metadata:
      labels:
        app: secret-demo
    spec:
      containers:
        - name: app
          image: busybox
          command: ["sh", "-c", "echo The app is running! && sleep 3600"]
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          volumeMounts:
            - name: secret-volume
              mountPath: "/etc/secrets"
              readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: db-credentials
