# This file contains a Kubernetes NetworkPolicy example that restricts traffic
# to a PostgreSQL database pod, allowing only web pods to communicate with it.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: web-db-policy
  namespace: k8s-demo
spec:
  podSelector:
    matchLabels:
      role: db
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              role: web
      ports:
        - protocol: TCP
          port: 5432
