# This file contains a Kubernetes NetworkPolicy example that restricts traffic
# to a PostgreSQL database pod, allowing only web pods to communicate with it.
apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  namespace: k8s-demo
  labels:
    role: web
spec:
  containers:
    - name: web
      image: nginx:1.21
---
apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  namespace: k8s-demo
  labels:
    role: db
spec:
  containers:
    - name: db
      image: postgres:13
      env:
        - name: POSTGRES_PASSWORD
          value: "postgres"
      ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Pod
metadata:
  name: other-pod
  namespace: k8s-demo
  labels:
    role: other
spec:
  containers:
    - name: other
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
